collegefootballpick10/urls.py
import sys
import os
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
import pick10.views

registration_backend_string = 'registration.backends.simple.urls'
if os.environ['COLLEGEFOOTBALLPICK10_REGISTRATION_BACKEND']:
    registration_backend_string = registration_backend_string.replace('simple', os.environ['COLLEGEFOOTBALLPICK10_REGISTRATION_BACKEND'])

urlpatterns = [
    # Examples:
    #url(r'^admin/password_reset/$', auth_views.password_reset, name='admin_password_reset'),
    #url(r'^admin/password_reset/done/$', auth_views.password_reset_done, name='admin_password_reset_done'),
    url(r'^admin/password_reset/$', auth_views.PasswordChangeView.as_view(), name='admin_password_reset'),
    url(r'^admin/password_reset/done/$', auth_views.PasswordChangeDoneView.as_view(), name='admin_password_reset_done'),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', admin.site.urls),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    #url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^$', pick10.views.home, name='home'),
    url(r'^pick10/', include('pick10.urls')),
    url(r'^accounts/', include(registration_backend_string)),
]

pick10/urls.py
from django.conf.urls import url
from .views import index
from .views import profile
from .views import commissioner
from .views import create_week
from .views import edit_week_sel
from .views import edit_week
from .views import set_week_winner
from .views import overall_results
from .views import week_results
from .views import tiebreak
from .views import update_games
from .views import player_results
from .views import player_stats
from .views import enter_picks
from .views import update_pages
from .views import update_week
from .views import update_tiebreak
from .views import update_overall

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^profile$', profile, name='profile'),
    url(r'^commissioner$', commissioner, name='commissioner'),
    url(r'^commissioner/createweek$', create_week, name='create_week'),
    url(r'^commissioner/editweek$', edit_week_sel, name='edit_week_sel'),
    url(r'^commissioner/editweek/(?P<year>[0-9]{4})/week/(?P<week_number>[0-9]{1,2})$', edit_week, name='edit_week'),
    url(r'^commissioner/weekwinner/(?P<year_num>[0-9]{4})/week/(?P<week_num>[0-9]{1,2})$', set_week_winner, name='set_week_winner'),
    url(r'^(?P<year>[0-9]{4})/results$', overall_results, name='overall_results'),
    url(r'^(?P<year>[0-9]{4})/week/(?P<week_number>[0-9]{1,2})/results$', week_results, name='week_results'),
    url(r'^(?P<year>[0-9]{4})/week/(?P<week_number>[0-9]{1,2})/tiebreak$', tiebreak, name='tiebreak'),
    url(r'^(?P<year>[0-9]{4})/week/(?P<week_number>[0-9]{1,2})/games$', update_games, name='update_games'),
    url(r'^(?P<year>[0-9]{4})/week/(?P<week_number>[0-9]{1,2})/player/(?P<player_id>[0-9]+)/results$', player_results, name='player_results'),
    url(r'^(?P<year>[0-9]{4})/week/(?P<week_number>[0-9]{1,2})/player/(?P<player_id>[0-9]+)/picks$', enter_picks, name='enter_picks'),
    url(r'^(?P<year>[0-9]{4})/week/(?P<week_number>[0-9]{1,2})/update$', update_pages, name='update_pages'),
    url(r'^(?P<year>[0-9]{4})/week/(?P<week_number>[0-9]{1,2})/update/week$', update_week, name='update_week'),
    url(r'^(?P<year>[0-9]{4})/week/(?P<week_number>[0-9]{1,2})/update/tiebreak$', update_tiebreak, name='update_tiebreak'),
    url(r'^(?P<year>[0-9]{4})/update/overall$', update_overall, name='update_overall'),
    url(r'^stats/player/(?P<player_id>[0-9]+)/all$', player_stats, name='player_stats'),
]

trunk/django/collegefootballpick10/collegefootballpick10/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'collegefootballpick10.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

pick10/models.py
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import six

import itertools
import random
try:
    from itertools import izip as zip
except ImportError:
    pass
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible

import pytz
from datetime import datetime, timedelta

def create_a_kickoff_time(yearnum, weeknum, gamenum):
    """Given a year, week, game calculate an appropriate kickoff time
    with timezone.
    """
    # Start by getting noon Jan 1, year
    dt = datetime(yearnum, 1, 1, 12, 0, 0, 0, pytz.timezone('EST'))
    # Figure out the first Saturday
    if dt.isoweekday() == 6:
        days_to_add = 6
    else:
        days_to_add = 5 - dt.weekday()
    dt += timedelta(days=days_to_add)
    # Forward to week 35 + weeknum
    dt += timedelta(days=7*(34 + weeknum - 1))

    return dt + timedelta(hours=gamenum)

def calc_default_pick_deadline():
    # The idea behind this is to grab the current day, then figure out the
    # next Thursday and use 4:00pm in the US/Eastern timezone.
    # Start with the current datetime
    naive_dt_now = datetime.now()
    # Figure out how many days to add to get to the next Thursday
    days_to_add = 3 - naive_dt_now.weekday()
    if days_to_add < 0:
        days_to_add += 7
    # Create a naive datetime corresponding to next Thursday at 4:00pm
    naive_dt_deadline = datetime(naive_dt_now.year, naive_dt_now.month, naive_dt_now.day, 16, 0, 0) + timedelta(days=days_to_add)
    # Localize it assuming US/Eastern time zone
    deadline = pytz.timezone('US/Eastern').localize(naive_dt_deadline)
    return deadline

def get_pick_deadline(yearnum=0, weeknum=0):
    '''Returns a value for pick_deadline as follows:
        1. If the current year/week has any games with kickoffs assigned, use the earliest kickoff.
        2. If the current year/week has a pick_deadline, return that.
        3. Call calc_default_pick_deadline and return that.
    '''
    if not yearnum or not weeknum or yearnum not in get_yearlist() or weeknum not in get_weeklist(yearnum):
        return calc_default_pick_deadline()

    gameobjs = get_games(yearnum, weeknum)
    kickoffs = sorted([getattr(g, 'kickoff') for g in gameobjs if getattr(g, 'kickoff') is not None])
    if kickoffs:
        return kickoffs[0]

    weekobj = get_week(yearnum, weeknum)
    if weekobj and getattr(weekobj, 'pick_deadline'):
        return getattr(weekobj, 'pick_deadline')


@python_2_unicode_compatible
class Year(models.Model):
    yearnum = models.IntegerField()
    entry_fee = models.DecimalField(default=10.0, decimal_places=2, max_digits=6)
    payout_week = models.DecimalField(default=15.0, decimal_places=2, max_digits=6)
    payout_first = models.DecimalField(default=0.0, decimal_places=2, max_digits=7)
    payout_second = models.DecimalField(default=0.0, decimal_places=2, max_digits=7)
    payout_third = models.DecimalField(default=0.0, decimal_places=2, max_digits=7)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = '1. Years'

    def __str__(self):
        return 'Year %d'%(self.yearnum,)

@python_2_unicode_compatible
class Player(models.Model):
    public_name = models.CharField(max_length=100, null=True, blank=True, default='')
    private_name = models.CharField(max_length=100, null=True, blank=True, default='')
    ss_name = models.CharField(max_length=100, null=True, blank=True, default='')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = '2. Players'
        ordering = ('ss_name', 'private_name',)

    def __str__(self):
        return '%s/%s/%s'%(self.private_name, self.public_name, self.ss_name)

@python_2_unicode_compatible
class PlayerYear(models.Model):
    player = models.ForeignKey('Player', on_delete=models.CASCADE)
    year = models.ForeignKey('Year', on_delete=models.CASCADE)
    first_place = models.BooleanField(default=False)
    second_place = models.BooleanField(default=False)
    third_place = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = '3. PlayerYears'

    def __str__(self):
        return '%s:%s'%(self.player.private_name, self.year.yearnum,)

@python_2_unicode_compatible
class Conference(models.Model):
    conf_name = models.CharField(max_length=40)                            # Conference name, 'Southeastern'
    div_name = models.CharField(max_length=40, null=True, blank=True, default='')      # Division name, 'East'
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = '4. Conferences'

    def __str__(self):
        return '%s %s'%(self.conf_name, self.div_name,)

@python_2_unicode_compatible
class Team(models.Model):
    team_name = models.CharField(max_length=40)                            # Team name, 'South Carolina'
    mascot = models.CharField(max_length=40)                               # Team mascot, 'Gamecocks'
    #TODO Save helmet field for later.
    #helmet = models.ImageField()                                          # Helmet pic, local file (.png, .gif, .jpg)
    conference = models.ForeignKey('Conference', default=None, on_delete=models.CASCADE)             # Pointer back to Conference entry
    current = models.BooleanField(default=True)                            # True if team should be included in selection lists
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = '5. Teams'

    def __str__(self):
        return '%s %s'%(self.team_name, self.mascot,)

@python_2_unicode_compatible
class Week(models.Model):
    year = models.ForeignKey('Year', on_delete=models.CASCADE)                                        # Season year corresponding to this week
    weeknum = models.IntegerField()                                         # Week number within the season
    winner = models.ForeignKey(Player, null=True, blank=True, default=None, on_delete=models.CASCADE) # Link to Player who won the week
    pick_deadline = models.DateTimeField(null=True, blank=True)             # When generating a new Week, use get_default_pick_deadline()
    lock_picks = models.BooleanField(default=False)                         # Commissioner sets to False once games are finalized and picks can begin
    lock_scores = models.BooleanField(default=False)                        # Commissioner sets to True, after which only commissioner can update scores
    #created = models.DateTimeField(auto_now=False, auto_now_add=True)
    #updated = models.DateTimeField(auto_now=True, auto_now_add=True)
    created = models.DateTimeField(editable=False)
    updated = models.DateTimeField()

    def save(self, *args, **kwargs):
        '''On save, update timestamps'''
        rightnow = timezone.now()
        if not self.id:
            self.created = rightnow
        self.updated = rightnow
        return super(Week, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = '6. Weeks'

    def __str__(self):
        return 'Year=%d, Week=%d'%(self.year.yearnum, self.weeknum,)

@python_2_unicode_compatible
class Game(models.Model):
    week = models.ForeignKey('Week', on_delete=models.CASCADE)                                        # Pointer back to Week entry
    gamenum = models.IntegerField(default=0)                                # Game number within the week (ie. 1-10)
    team1 = models.ForeignKey('Team', related_name='team1', on_delete=models.CASCADE)                 # Pointer back to Team entry
    team2 = models.ForeignKey('Team', related_name='team2', on_delete=models.CASCADE)                 # Pointer back to Team entry
    team1_actual_points = models.IntegerField(default=-1)                   # Actual points scored 
    team2_actual_points = models.IntegerField(default=-1)                   # Actual points scored 
    favored = models.IntegerField(default=0)                                # Indicates which team is the favorite
    spread = models.DecimalField(default=0.0, decimal_places=1, max_digits=4) # Point spread added to underdog's score to determine winner
    kickoff = models.DateTimeField(null=True, blank=True)                   # Kickoff date/time
    game_state = models.IntegerField(default=0)                             # Enum (0=invalid, 1=not_started, 2=in_progress, 3=final)
    quarter = models.CharField(max_length=3, default='')                    # Used to indicate game progress ('1st', '2nd', '3rd', '4th', 'OT')
    time_left = models.CharField(max_length=10, default='')                 # Time left in the quarter (MM:SS)
    winner = models.IntegerField(default=0)                                 # Winner according to spread
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = '7. Games'

    def __str__(self):
        return 'Year=%d, Week=%d, Game=%d'%(self.week.year.yearnum, self.week.weeknum, self.gamenum,)

@python_2_unicode_compatible
class Pick(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)                                 # Link to player for which this pick applies
    game = models.ForeignKey('Game', on_delete=models.CASCADE)                                   # Link to game for which this pick applies
    winner = models.IntegerField(default=0)                            # Indicates which team was picked to win (1 or 2)

trunk/django/collegefootballpick10/pick10/views.py
from django.shortcuts import render

# Create your views here.

templates/pick10/bad_week.html
{% extends 'base.html' %}

{% block header_text %}College Football Pick 10{% endblock %}

{% block body_block %}
<hr>
<div style="color: red; font-family: Helvetica; font-size: 12pt; font-weight: 100;">
    Cannot find {{year}} week {{week_number}} in the database.
</div>
{% endblock %}

templates/pick10/edit_week_form.html
{% extends 'base.html' %}

{% block body_block %}
<link href="/static/edit_picks.css" rel="stylesheet" type="text/css" media="all">

<h2>Commissioner Edit {{year}} Week {{week_number}}</h2><p>NOTE: Kickoffs to be entered using Eastern timezone. Format: YYYY-MM-DD HH:MM:SS</p>

<form id="edit_week_form" action="{% url 'edit_week' year week_number %}" method="post">
    {% csrf_token %}
    {% if form.errors %}
    {{form.non_field_errors}}
    {% endif %}
    <input class="btn-primary btn-lg" type="submit" {% if commish_can_post %}value="Submit"{% else %}value="Disabled" disabled="disabled"{% endif %} />
    <hr></hr>
    <div class="row csscls_logistics">
        <div class="col-md-6">
            <p><label for="id_lock_picks_0">Lock picks:</label>{{form.lock_picks}}</p>
        </div>
        <div class="col-md-6">
            <div id="vertical_center">
            <p><label for="id_pick_deadline">Pick deadline:</label>{{form.pick_deadline}}</p>
            </div>
        </div>
    </div>
    <hr></hr>
    <div class="row csscls_game_odd">
        <div class="col-md-3">
            <p><label for="id_game1_team1">Game1 team1:</label>{{form.game1_team1}}</p>
            <p><label for="id_game1_team2">Game1 team2:</label>{{form.game1_team2}}</p>
        </div>
        <div class="col-md-3">
            <p><label for="id_game1_favored_0">Game1 favored:</label>{{form.game1_favored}}</p>
            {{form.game1_favored.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game1_spread">Game1 spread:</label>{{form.game1_spread}}</p>
            {{form.game1_spread.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game1_kickoff">Game1 kickoff:</label>{{form.game1_kickoff}}</p>
            {{form.game1_kickoff.errors}}
        </div>
    </div>
    <hr></hr>
    <div class="row csscls_game_even">
        <div class="col-md-3">
            <p><label for="id_game2_team1">Game2 team1:</label>{{form.game2_team1}}</p>
            <p><label for="id_game2_team2">Game2 team2:</label>{{form.game2_team2}}</p>
        </div>
        <div class="col-md-3">
            <p><label for="id_game2_favored_0">Game2 favored:</label>{{form.game2_favored}}</p>
            {{form.game2_favored.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game2_spread">Game2 spread:</label>{{form.game2_spread}}</p>
            {{form.game2_spread.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game2_kickoff">Game2 kickoff:</label>{{form.game2_kickoff}}</p>
            {{form.game2_kickoff.errors}}
        </div>
    </div>
    <hr></hr>
    <div class="row csscls_game_odd">
        <div class="col-md-3">
            <p><label for="id_game3_team1">Game3 team1:</label>{{form.game3_team1}}</p>
            <p><label for="id_game3_team2">Game3 team2:</label>{{form.game3_team2}}</p>
        </div>
        <div class="col-md-3">
            <p><label for="id_game3_favored_0">Game3 favored:</label>{{form.game3_favored}}</p>
            {{form.game3_favored.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game3_spread">Game3 spread:</label>{{form.game3_spread}}</p>
            {{form.game3_spread.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game3_kickoff">Game3 kickoff:</label>{{form.game3_kickoff}}</p>
            {{form.game3_kickoff.errors}}
        </div>
    </div>
    <hr></hr>
    <div class="row csscls_game_even">
        <div class="col-md-3">
            <p><label for="id_game4_team1">Game4 team1:</label>{{form.game4_team1}}</p>
            <p><label for="id_game4_team2">Game4 team2:</label>{{form.game4_team2}}</p>
        </div>
        <div class="col-md-3">
            <p><label for="id_game4_favored_0">Game4 favored:</label>{{form.game4_favored}}</p>
            {{form.game4_favored.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game4_spread">Game4 spread:</label>{{form.game4_spread}}</p>
            {{form.game4_spread.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game4_kickoff">Game4 kickoff:</label>{{form.game4_kickoff}}</p>
            {{form.game4_kickoff.errors}}
        </div>
    </div>
    <hr></hr>
    <div class="row csscls_game_odd">
        <div class="col-md-3">
            <p><label for="id_game5_team1">Game5 team1:</label>{{form.game5_team1}}</p>
            <p><label for="id_game5_team2">Game5 team2:</label>{{form.game5_team2}}</p>
        </div>
        <div class="col-md-3">
            <p><label for="id_game5_favored_0">Game5 favored:</label>{{form.game5_favored}}</p>
            {{form.game5_favored.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game5_spread">Game5 spread:</label>{{form.game5_spread}}</p>
            {{form.game5_spread.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game5_kickoff">Game5 kickoff:</label>{{form.game5_kickoff}}</p>
            {{form.game5_kickoff.errors}}
        </div>
    </div>
    <hr></hr>
    <div class="row csscls_game_even">
        <div class="col-md-3">
            <p><label for="id_game6_team1">Game6 team1:</label>{{form.game6_team1}}</p>
            <p><label for="id_game6_team2">Game6 team2:</label>{{form.game6_team2}}</p>
        </div>
        <div class="col-md-3">
            <p><label for="id_game6_favored_0">Game6 favored:</label>{{form.game6_favored}}</p>
            {{form.game6_favored.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game6_spread">Game6 spread:</label>{{form.game6_spread}}</p>
            {{form.game6_spread.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game6_kickoff">Game6 kickoff:</label>{{form.game6_kickoff}}</p>
            {{form.game6_kickoff.errors}}
        </div>
    </div>
    <hr></hr>
    <div class="row csscls_game_odd">
        <div class="col-md-3">
            <p><label for="id_game7_team1">Game7 team1:</label>{{form.game7_team1}}</p>
            <p><label for="id_game7_team2">Game7 team2:</label>{{form.game7_team2}}</p>
        </div>
        <div class="col-md-3">
            <p><label for="id_game7_favored_0">Game7 favored:</label>{{form.game7_favored}}</p>
            {{form.game7_favored.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game7_spread">Game7 spread:</label>{{form.game7_spread}}</p>
            {{form.game7_spread.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game7_kickoff">Game7 kickoff:</label>{{form.game7_kickoff}}</p>
            {{form.game7_kickoff.errors}}
        </div>
    </div>
    <hr></hr>
    <div class="row csscls_game_even">
        <div class="col-md-3">
            <p><label for="id_game8_team1">Game8 team1:</label>{{form.game8_team1}}</p>
            <p><label for="id_game8_team2">Game8 team2:</label>{{form.game8_team2}}</p>
        </div>
        <div class="col-md-3">
            <p><label for="id_game8_favored_0">Game8 favored:</label>{{form.game8_favored}}</p>
            {{form.game8_favored.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game8_spread">Game8 spread:</label>{{form.game8_spread}}</p>
            {{form.game8_spread.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game8_kickoff">Game8 kickoff:</label>{{form.game8_kickoff}}</p>
            {{form.game8_kickoff.errors}}
        </div>
    </div>
    <hr></hr>
    <div class="row csscls_game_odd">
        <div class="col-md-3">
            <p><label for="id_game9_team1">Game9 team1:</label>{{form.game9_team1}}</p>
            <p><label for="id_game9_team2">Game9 team2:</label>{{form.game9_team2}}</p>
        </div>
        <div class="col-md-3">
            <p><label for="id_game9_favored_0">Game9 favored:</label>{{form.game9_favored}}</p>
            {{form.game9_favored.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game9_spread">Game9 spread:</label>{{form.game9_spread}}</p>
            {{form.game9_spread.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game9_kickoff">Game9 kickoff:</label>{{form.game9_kickoff}}</p>
            {{form.game9_kickoff.errors}}
        </div>
    </div>
    <hr></hr>
    <div class="row csscls_game_even">
        <div class="col-md-3">
            <p><label for="id_game10_team1">Game10 team1:</label>{{form.game10_team1}}</p>
            <p><label for="id_game10_team2">Game10 team2:</label>{{form.game10_team2}}</p>
        </div>
        <div class="col-md-3">
            <p><label for="id_game10_favored_0">Game10 favored:</label>{{form.game10_favored}}</p>
            {{form.game10_favored.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game10_spread">Game10 spread:</label>{{form.game10_spread}}</p>
            {{form.game10_spread.errors}}
        </div>
        <div class="col-md-3">
            <p><label for="id_game10_kickoff">Game10 kickoff:</label>{{form.game10_kickoff}}</p>
            {{form.game10_kickoff.errors}}
        </div>
    </div>
    <hr></hr>
    <input class="btn-primary btn-lg" type="submit" {% if commish_can_post %}value="Submit"{% else %}value="Disabled" disabled="disabled"{% endif %} />
</form>

{% endblock %}

templates/pick10/enter_picks_error.html
{% extends "base.html" %}

{% block header_text %}College Football Pick 10{% endblock %}

{% block side_block %}
    {% include "pick10/year_sidebar.html" %}
    {% endblock %}

{% block body_header_block %}
    {% include "pick10/week_navbar.html" %}
    <br>
{% endblock %}

{% block body_block %}
<link href="/static/title_bar.css" rel="stylesheet" type="text/css" media="all">
<link href="/static/error.css" rel="stylesheet" type="text/css" media="all">
    {% if error == "user_not_participant" %}
        <div id="error-msg">User {{user.username}} is not a participant in the pool.</div>
    {% endif %}
    {% if error == "user_player_mismatch" %}
        <div id="error-msg">Player {{player_id}} does not match the logged in user.</div>
        <div id="error-msg">A user can only access their own enter picks page.</div>
    {% endif %}
    {% if error == "picks_locked" %}
        <div id="error-msg">Picks are currently locked and cannot be entered.</div>
    {% endif %}
    {% if error == "after_pick_deadline" %}
        <div id="error-msg">Pick deadline: {{deadline}}.</div><br>
        <div id="error-msg">The pick deadline has expired.  Picks can no longer be entered.</div>
    {% endif %}
    {% if error == "week_in_progress" %}
        <div id="error-msg">The week is currently in progress. No picks can be made.</div>
    {% endif %}
    {% if error == "week_final" %}
        <div id="error-msg">The week is final. No picks can be made.</div>
    {% endif %}
    {% if error == "week_not_setup" %}
        <div id="error-msg">The week is currently being setup.</div>
    {% endif %}
{% endblock %}

templates/pick10/error_message.html
{% extends "base.html" %}

{% block body_block %}
<hr>
<link href="/stylesheets/error.css" rel="stylesheet" type="text/css" media="all">
<div id="error-msg">{{message}}</div>
{% endblock %}

templates/pick10/overall_results.html
{% extends 'base.html' %}

{% block header_text %}{{year}} Leaderboard{% endblock %}

{% block side_block %}
    {{ side_block_content|safe }}
{% endblock %}

{% block body_header_block %}
    <div id="page-title">{{year}} Leaderboard</div>
    {% include "pick10/week_navbar.html" %}
    <br>
{% endblock %}

{% block body_block %}
    {{ body_content|safe }}
    <br><br>
{% endblock %}

{% block script_block %}
    <script>
        $(document).ready(function() {
                $("#overall_results_table").tablesorter();
            }
        );
    </script>
    <script>
        var player_id = {{player_id}};
        $(document).ready(function() {
            highlight_player_row(player_id);
        });
    </script>
{% endblock %}

templates/pick10/overall_results_body.html
    <link href="/static/title_bar.css" rel="stylesheet" type="text/css" media="all">
    <link href="/static/overall_results_3.css" rel="stylesheet" type="text/css" media="all">
    <script>
function highlight_player_row(player_id) {
    if (player_id == null) {
        return;
    }

    var row_id = "#player_" + player_id;

    // red
    var color = "#b94a48";
    var bgcolor = "#f2dede";

    $(row_id).find("td").css("color",color);
    $(row_id).find("td").css("background-color",bgcolor);
    $(row_id).find("a").css("color",color);
    $(row_id).find("a").css("background-color",bgcolor);
}
    </script>
<div id="results">
    {{ content|safe }}
</div>

templates/pick10/set_week_winner_form.html
{% extends 'base.html' %}

{% block body_block %}

<h2>Set Week Winner</h2>
<p>Form to set the week winner (commissioners-only).</p>

<h3>Choose winner for {{year_num}} week {{week_num}}:</h3>
<form id="set_week_winner_form" action="{% url 'set_week_winner' year_num week_num %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

templates/pick10/tiebreak.html
{% extends 'base.html' %}

{% block header_text %}Week {{week_number}} Tiebreaker{% endblock %}

{% block side_block %}
    {{ side_block_content|safe }}
{% endblock %}

{% block body_header_block %}
    <div id="page-title">Week {{week_number}} Tiebreaker</div>
    {% include "pick10/week_navbar.html" %}
    <br>
{% endblock %}

{% block body_block %}
    {{ body_content|safe }}
{% endblock %}